/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define TOTAL_MMAP_FILES      2
#define MMAP_CHECKSUM         0x4FFE

enum MMAP_FILES {
    MMAP_1528966158_SVG = 0,   /*!< 1528966158.svg */
    MMAP_TIGER_SVG = 1,   /*!< tiger.svg */
};
